version: '2'
services:
    forralhipster-app:
        image: forralhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://forralhipster-mssql:1433;database=jhitest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    forralhipster-mssql:
        extends:
            file: mssql.yml
            service: forralhipster-mssql
